### ISSUE TITLE
Support for Raspberry Pi 4

### ISSUE THREAD

**Issue by MillerTime72** [Picovoice/octopus#106]
Hi,

I've been using a lot of your stuff to create various projects on a Raspberry Pi 4. All your libraries have worked amazingly in the past. I've now become interested in using `pvoctopus` to build a personal application. It installs fine on my pi, but when I go to import it into a new file I receive the following error.

`
Traceback (most recent call last):
  File "/home/millertime/Desktop/Project/main.py", line 1, in <module>
    import pvoctopus
  File "/home/millertime/Desktop/Project/venv/lib/python3.9/site-packages/pvoctopus/__init__.py", line 17, in <module>
    LIBRARY_PATH = pv_library_path('')
  File "/home/millertime/Desktop/Project/venv/lib/python3.9/site-packages/pvoctopus/util.py", line 46, in pv_library_path
    raise NotImplementedError('Unsupported platform.')
NotImplementedError: Unsupported platform.
`

It's pretty clear what this means; `pvoctopus` isn't supported for my platform. I was wondering if there are currently any plans to make support? If not, are there any packages I can install or hacks I can do to make this work? Thanks a lot, love your stuff.

**Comment by laves** [comment]
Hi @MillerTime72 - glad you're enjoying our stuff. We don't currently release Octopus libraries built for rpi. In general, most use cases for Octopus involve large corpora of audio, so single-board/microcontroller hasn't been a priority for us. Just curious - what is your use case?

**Comment by MillerTime72** [comment]
I’d like to try and make an application to search through video files by entering key words and phrases.

**Comment by laves** [comment]
I'll bring it up to the product team and see if we can get it on the roadmap. If you're an Enterprise customer, feel free to reach out to sales to request this as part of your package.

**Comment by MillerTime72** [comment]
No, I’m not a paying customer. Thanks a lot for considering this.

**Comment by kenarsa** [comment]
closing due to inactivity. re-open if needed.
